image: golang:1.22.6

# move this to gitlab env variable
variables:
  SERVER_IP: ""
  SERVER_USER: ""


# ci process will be running on the branch with prefix feature (feature-testci)
workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_VARIABLE: "deploy-production"  # Override globally-defined DEPLOY_VARIABLE
    - if: $CI_COMMIT_REF_NAME =~ /feature/
      variables:
        IS_A_FEATURE: "true"                  # Define a new variable.
    - when: always

stages:
  - lint
  - test
  - build
  - deploy

test_lint:
  except:
    - main
  stage: lint
  image: golangci/golangci-lint
  script:
    - golangci-lint run

test_code:
  except:
    - main
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test $(go list ./... | grep -v /vendor/) -v -test.short
    - go test ./... -coverprofile=coverage.out
    - go tool cover -html="coverage.out"

build_artefact:
  except:
    - main
  stage: build
  script:
    - mkdir bin
    - mkdir bin/win
    - mkdir bin/mac
    - mkdir bin/linux
    - GOOS=windows GOARCH=amd64 go build -o bin/win ./...
    - GOOS=darwin GOARCH=amd64 go build -o bin/mac ./...
    - GOOS=linux GOARCH=amd64 go build -o bin/linux ./...
  artifacts:
    paths:
      - bin

build_image:
  except:
    - main
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  except:
    - main
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $SERVER_USER@$SERVER_IP "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker rmi $CI_REGISTRY_IMAGE:latest &&
      docker run -d --name=dating-api -p 8080:8080 $CI_REGISTRY_IMAGE:latest"
  when: manual
